services:
    auth:
        container_name: fritata-backend-auth
        image: <DOCKERHUB-USERNAME>/fritata-backend-auth:latest
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - users

    posts:
        container_name: fritata-backend-posts
        image: <DOCKERHUB-USERNAME>/fritata-backend-posts:latest
        ports:
            - 8020:8020
        env_file:
            - ./.env
        depends_on:
            - users

    users:
        container_name: fritata-backend-users
        image: <DOCKERHUB-USERNAME>/fritata-backend-users:latest
        ports:
            - 8010:8010
            - 8011:8011
        env_file:
            - ./.env