apiVersion: v1
kind: Namespace
metadata:
  name: fritata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: fritata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: subbyte/fritata-backend-auth:latest
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: fritata-env
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: fritata
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  namespace: fritata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: subbyte/fritata-backend-posts:latest
        ports:
        - containerPort: 8020
        envFrom:
          - configMapRef:
              name: fritata-env
---
apiVersion: v1
kind: Service
metadata:
  name: posts
  namespace: fritata
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: fritata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: subbyte/fritata-backend-users:latest
        ports:
        - containerPort: 8010
        - containerPort: 8011
        envFrom:
          - configMapRef:
              name: fritata-env
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: fritata
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
      name: external
    - protocol: TCP
      port: 8011
      targetPort: 8011
      name: internal