name: Build and Push Docker Images to Docker Hub

on:
    push:
        branches:
            - main

env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        name: Build and Push Docker Images to Docker Hub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              id: checkout_code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              id: login_docker_hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER_NAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and Push Auth Service
              run: |
                  docker build -f ./services/auth/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA .
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA

            - name: Build and Push Posts Service
              run: |
                  docker build -f ./services/posts/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA .
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA

            - name: Build and Push Users Service
              run: |
                  docker build -f ./services/users/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA .
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA

            - name: Logout from Docker Hub
              run: docker logout

            - name: End
              run: echo "Docker image pushed to Docker Hub successfully"
