name: Build and Push Docker Images to Docker Hub

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        name: Build and Push Docker Images to Docker Hub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              id: checkout_code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              id: login_docker_hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER_NAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and Push Auth Service
              run: |
                  docker build -f ./services/auth/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA .
                  docker tag ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:latest
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:latest

            - name: Build and Push Posts Service
              run: |
                  docker build -f ./services/posts/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA .
                  docker tag ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:latest
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:latest

            - name: Build and Push Users Service
              run: |
                  docker build -f ./services/users/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA .
                  docker tag ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:latest
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA
                  docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:latest

            - name: Logout from Docker Hub
              run: docker logout

            - name: End
              run: echo "Docker image pushed to Docker Hub successfully"
    deploy:
      name: Deploy to Azure VM
      needs: build-and-push
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Copy Kubernetes Config to VM
          env:
            SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
          run: |
            echo "$SSH_KEY" > vm_key.pem
            chmod 600 vm_key.pem
            scp -o StrictHostKeyChecking=no -i vm_key.pem kubernetes-deploy.yaml ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_PUBLIC_IP }}:~/kubernetes-deploy.yaml

        - name: Deploy to Kubernetes
          env:
            SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
          run: |
            ssh -o StrictHostKeyChecking=no -i vm_key.pem ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_PUBLIC_IP }} << 'EOF'
              docker pull ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:latest
              docker pull ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:latest
              docker pull ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:latest

              kubectl delete configmap fritata-env -n fritata
              kubectl create configmap fritata-env --from-env-file=/home/${{ secrets.AZURE_VM_USERNAME }}/.env -n fritata

              kubectl apply -f kubernetes-deploy.yaml
            EOF

            rm vm_key.pem