name: Build and Push Docker Images to Docker Hub

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Docker Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Build Auth Service Image
              run: docker build -f ./services/auth/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA .

            - name: Build Posts Service Image
              run: docker build -f ./services/posts/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA .

            - name: Build Users Service Image
              run: docker build -f ./services/users/Dockerfile -t ${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA

            - name: Save Built Images
              run: |
                  echo "AUTH_IMAGE=${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-auth:$GITHUB_SHA" >> $GITHUB_ENV
                  echo "POSTS_IMAGE=${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-posts:$GITHUB_SHA" >> $GITHUB_ENV
                  echo "USERS_IMAGE=${{ secrets.DOCKER_HUB_USER_NAME }}/fritata-backend-users:$GITHUB_SHA" >> $GITHUB_ENV

    publish:
        name: Publish Docker Images
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER_NAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Push Auth Service Image
              run: docker push ${{ env.AUTH_IMAGE }}

            - name: Push Posts Service Image
              run: docker push ${{ env.POSTS_IMAGE }}

            - name: Push Users Service Image
              run: docker push ${{ env.USERS_IMAGE }}

            - name: Logout from Docker Hub
              run: docker logout
